print ("This is a sample python script")
name = input("What is your name? ")
phone = input ('Phone 😍 => ')
address = input ('Address ->     ')
city = input ('City ->  ')
state = input ('State------>        ')
print (name, phone)
print (address, city, state)